/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stagiare;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import javax.swing.JTable;

/**
 *
 * @author HP
 */
public class TEST1 extends javax.swing.JFrame {

    /**
     * Creates new form TEST1
     */
    private DefaultTableModel dt;
    private int id;
    private String nom, prenom, sexe;
    private String service,mat;
    private String dure;
    
    private int i;
    
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    
    
    
    public TEST1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmat = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtduree = new javax.swing.JTextField();
        combservice = new javax.swing.JComboBox<>();
        jrb1 = new javax.swing.JCheckBox();
        jrb2 = new javax.swing.JCheckBox();
        btnn1 = new javax.swing.JButton();
        btnn3 = new javax.swing.JButton();
        btnn2 = new javax.swing.JButton();
        btnn4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstg = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        combrech = new javax.swing.JComboBox<>();
        txtrech = new javax.swing.JTextField();
        btnn5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 590));
        setPreferredSize(new java.awt.Dimension(890, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel1.setText("Gestion de stagiaires");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 121, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Matricule:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 148, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nom:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 179, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Prénom: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 208, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Département: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 237, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Durée du stage:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Sexe:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txtmat.setBackground(new java.awt.Color(153, 153, 153));
        txtmat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtmat.setForeground(new java.awt.Color(0, 0, 102));
        txtmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatActionPerformed(evt);
            }
        });
        getContentPane().add(txtmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 148, 137, -1));

        txtnom.setBackground(new java.awt.Color(153, 153, 153));
        txtnom.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtnom.setForeground(new java.awt.Color(0, 0, 102));
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 177, 137, -1));

        txtprenom.setBackground(new java.awt.Color(153, 153, 153));
        txtprenom.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtprenom.setForeground(new java.awt.Color(0, 0, 102));
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 206, 137, -1));

        txtid.setBackground(new java.awt.Color(153, 153, 153));
        txtid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 102));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 119, 137, -1));

        txtduree.setBackground(new java.awt.Color(153, 153, 153));
        txtduree.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtduree.setForeground(new java.awt.Color(0, 0, 102));
        txtduree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdureeActionPerformed(evt);
            }
        });
        getContentPane().add(txtduree, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 265, 137, -1));

        combservice.setBackground(new java.awt.Color(153, 153, 153));
        combservice.setForeground(new java.awt.Color(0, 0, 102));
        combservice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatique", "Vente", "Production" }));
        getContentPane().add(combservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 235, 137, -1));

        jrb1.setBackground(new java.awt.Color(153, 153, 153));
        jrb1.setForeground(new java.awt.Color(255, 255, 255));
        jrb1.setText("Masculin");
        jrb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jrb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jrb2.setBackground(new java.awt.Color(153, 153, 153));
        jrb2.setForeground(new java.awt.Color(255, 255, 255));
        jrb2.setText("Féminin");
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jrb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        btnn1.setBackground(new java.awt.Color(153, 153, 153));
        btnn1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        btnn1.setForeground(new java.awt.Color(0, 0, 102));
        btnn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\adduser_4961.png")); // NOI18N
        btnn1.setText("Ajouter");
        btnn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn1MouseExited(evt);
            }
        });
        btnn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 372, 138, -1));

        btnn3.setBackground(new java.awt.Color(153, 153, 153));
        btnn3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        btnn3.setForeground(new java.awt.Color(0, 0, 102));
        btnn3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\deleteUser_4951.png")); // NOI18N
        btnn3.setText("Supprimer");
        btnn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn3MouseExited(evt);
            }
        });
        btnn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 428, -1, -1));

        btnn2.setBackground(new java.awt.Color(153, 153, 153));
        btnn2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        btnn2.setForeground(new java.awt.Color(0, 0, 102));
        btnn2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\editinguser_edituser_useedit_4520.png")); // NOI18N
        btnn2.setText("Modifier");
        btnn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn2MouseExited(evt);
            }
        });
        btnn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 372, 146, -1));

        btnn4.setBackground(new java.awt.Color(153, 153, 153));
        btnn4.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        btnn4.setForeground(new java.awt.Color(0, 0, 102));
        btnn4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\twoclockwisecirculararrowsoutline_80710.png")); // NOI18N
        btnn4.setText("Actualiser");
        btnn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn4MouseExited(evt);
            }
        });
        btnn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 428, 146, -1));

        tblstg.setBackground(new java.awt.Color(153, 153, 153));
        tblstg.setForeground(new java.awt.Color(0, 0, 102));
        tblstg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblstg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstg);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 119, 412, 197));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Recherche par:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 365, -1, -1));

        combrech.setBackground(new java.awt.Color(153, 153, 153));
        combrech.setForeground(new java.awt.Color(0, 0, 102));
        combrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Matricule", "Nom", "Prénom", "Département", "Durée de stage", "Sexe" }));
        getContentPane().add(combrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 334, 137, -1));

        txtrech.setBackground(new java.awt.Color(153, 153, 153));
        txtrech.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtrech.setForeground(new java.awt.Color(0, 0, 102));
        txtrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechActionPerformed(evt);
            }
        });
        getContentPane().add(txtrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 380, 137, -1));

        btnn5.setBackground(new java.awt.Color(153, 153, 153));
        btnn5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        btnn5.setForeground(new java.awt.Color(0, 0, 102));
        btnn5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\1490793870-user-interface25_82355.png")); // NOI18N
        btnn5.setText("Recherche");
        btnn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnn5MouseExited(evt);
            }
        });
        btnn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 345, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\print-printer-tool-with-printed-paper-outlined-symbol_icon-icons.com_57772.png")); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 130, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\siapc_background_03.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtdureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdureeActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
        // TODO add your handling code here:
        sexe=jrb2.getText();
    }//GEN-LAST:event_jrb2ActionPerformed

    private void txtrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechActionPerformed

    private void btnn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn5ActionPerformed
        // TODO add your handling code here:
        try{
        dt.setRowCount(0); //pour vider tableau 
    Statement st = con.createStatement();
        ResultSet rs = st.executeQuery( "SELECT * FROM stagiaire WHERE "+combo()
                +"  like '%"+txtrech.getText()+"%'" );
    
     while(rs.next()){
         id=rs.getInt(1);  
         mat = rs.getString("matricule"); 
         nom = rs.getString(3);
         prenom = rs.getString(4);
         service = rs.getString(5);
         dure = rs.getString(6);
         sexe=rs.getString(7);
            
            Object[] stg = {id,mat,nom,prenom,service,dure,sexe};
            dt.addRow(stg);
        }
     
        if (dt.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Aucun Stagiaire");
            Afficher(); // afficehr tout les stgs
        }else{
            i = 0;
            Deplacer(i);
        }
    
}catch (Exception m){JOptionPane.showMessageDialog(null, ""+m.getMessage());
System.err.println(m);  }

    }//GEN-LAST:event_btnn5ActionPerformed

    private void btnn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn4ActionPerformed
        // TODO add your handling code here:
        actualiser();
        Afficher();
    }//GEN-LAST:event_btnn4ActionPerformed

    private void btnn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn1MouseEntered
        // TODO add your handling code here:
        btnn1.setBackground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_btnn1MouseEntered

    private void btnn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn1MouseExited
        // TODO add your handling code here:
        btnn1.setBackground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnn1MouseExited

    private void btnn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn2MouseEntered
btnn2.setBackground(new java.awt.Color(102,102,102));        // TODO add your handling code here:
    }//GEN-LAST:event_btnn2MouseEntered

    private void btnn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn3MouseEntered
        // TODO add your handling code here:
        btnn3.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_btnn3MouseEntered

    private void btnn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn4MouseEntered
        // TODO add your handling code here:
        btnn4.setBackground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_btnn4MouseEntered

    private void btnn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn5MouseEntered
        // TODO add your handling code here:
        btnn5.setBackground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_btnn5MouseEntered

    private void btnn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn2MouseExited
        // TODO add your handling code here:
        btnn2.setBackground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnn2MouseExited

    private void btnn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn3MouseExited
        // TODO add your handling code here:
        btnn3.setBackground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnn3MouseExited

    private void btnn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn4MouseExited
        // TODO add your handling code here:
        btnn4.setBackground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnn4MouseExited

    private void btnn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnn5MouseExited
        // TODO add your handling code here:
        btnn1.setBackground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnn5MouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
        // connexion avec base de donnée stg
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stg1","root","");
      st = con.createStatement();
     
      jrbg.add(jrb1);
        jrbg.add(jrb2);
        //tng2.add(jrb5);
      
        dt = new DefaultTableModel();// dt c'est un variable pour stocké les element d'un tableau {ligne et colomn}
      
        dt.addColumn("ID");
        dt.addColumn("Matricule");
        dt.addColumn("Nom");
        dt.addColumn("Prénom");
        dt.addColumn("Département");
        dt.addColumn("Durée");
        dt.addColumn("Sexe");
       tblstg.setModel(dt);
        // afficehr la liste des stagiaires
        Afficher();
        // remplir les champs 
         i = 0;
        Deplacer(i);
    }catch(Exception e){
        System.out.printf("erreur   "+e.getMessage());//getMessage c'est une fonction  pour afficher l'Erreur ou se trouve ?!!!!!
        JOptionPane.showMessageDialog(null, "Erreur de connexion\n  "+ e.getMessage());
    }
    }//GEN-LAST:event_formWindowOpened

    private void tblstgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstgMouseClicked
        // TODO add your handling code here:
        try{
        i = tblstg.getSelectedRow(); // getSelectedRow() fonction nous retourne le ligne selectionner par l utilisateur
         
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur selectionnéé stg\n"+e.getMessage());
    }
    }//GEN-LAST:event_tblstgMouseClicked

    private void btnn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn1ActionPerformed
        // TODO add your handling code here:
         try{
   
String sql = "INSERT INTO stagiaire  (matricule,nom,prenom,service,duree_de_stage,sexe)VALUES (?,?,?,?,?,?)";
      PreparedStatement ps = con.prepareStatement(sql);
      ps.setString(1, txtmat.getText());
      ps.setString(2, txtnom.getText());
      ps.setString(3, txtprenom.getText());
      ps.setString(4, combservice.getSelectedItem().toString());
      ps.setString(5, txtduree.getText());
      ps.setString(6, sexe);
    
      
      ps.executeUpdate();
      Afficher(); // recharger la liste des stagiaires
            JOptionPane.showMessageDialog(null, "Stagiaire est ajouté");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur ajouter stg\n"+e.getMessage());
        System.err.println(""+e.getMessage());
    }

    }//GEN-LAST:event_btnn1ActionPerformed

    private void jrb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb1ActionPerformed
        // TODO add your handling code here:
        sexe=jrb1.getText();
    }//GEN-LAST:event_jrb1ActionPerformed

    private void btnn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn2ActionPerformed
        // TODO add your handling code here:
        try{ 
        // msg d confirmation !
        if (JOptionPane.showConfirmDialog(null, "confirmer la modification","modification sur un stagaire",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
           st.executeUpdate("UPDATE stagiaire SET matricule='"+txtmat.getText()+"',nom='"+txtnom.getText()
      +"',prenom='"+txtprenom.getText()+"',service='"+combservice.getSelectedItem().toString()
                   +"',duree_de_stage='"+txtduree.getText()+"',sexe='"+sexe
                   +"' WHERE id = "+ txtid.getText());       
           //lorseque en fait +txtfield.gettext+ en doit ecrit les appostrophe ""
  
           Afficher(); // recharger la liste des stagiaires
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur modifier stg\n"+e.getMessage());
    }
    }//GEN-LAST:event_btnn2ActionPerformed

    private void btnn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn3ActionPerformed
        // TODO add your handling code here:
        try{
        if(JOptionPane.showConfirmDialog(null, "Attention!! Est-ce que vous êtes sûr de"
                + " vouloir supprimer ce stagiaire?","Supprimer stagaire",JOptionPane.YES_NO_OPTION)
                == JOptionPane.OK_OPTION){
   //si textfield id est vide ,on peux pas supprimmer
                st.executeUpdate("Delete from stagiaire where id = "+ txtid.getText());
                Afficher(); // recharger la liste des stagiaires ...
           
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur supprimer stg !\n"+e.getMessage());
    }
    }//GEN-LAST:event_btnn3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Liste des stagiaires: \n\n");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {
            tblstg.print(JTable.PrintMode.NORMAL, header, footer);

        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erreur d'impression", e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    String combo(){
switch(combrech.getSelectedIndex()){ 
        case 0: return "id"; 
        case 1: return "matricule";
        case 2: return "nom";
        case 3: return "prenom";
        case 4: return "service";
        case 5: return "duree_de_stage";
        case 6: return "sexe";
      }
      return "";
}
    
    private void Afficher(){
  
   txtid.setEnabled(false);
   
     try{
        dt.setRowCount(0); // vider la list des stagiaires.
        rs = st.executeQuery("Select * From stagiaire");
        
        while(rs.next()){
           id=rs.getInt("id");
            mat = rs.getString("matricule");
            nom = rs.getString("nom");
            prenom = rs.getString("prenom");
            service = rs.getString("service");
            dure = rs.getString("duree_de_stage");
            sexe = rs.getString("sexe");
            Object[] t = {id,mat,nom,prenom,service,dure,sexe};
            dt.addRow(t);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur afficher la liste des stagiaire\n"+e.getMessage());
    }
    }
    
    private void Deplacer(int i){
    try{
        
        
        txtid.setText(dt.getValueAt(i, 0).toString()); 
        txtmat.setText(dt.getValueAt(i, 1).toString()); // i represente numero d ligne ,et 0 1 .. colonne
        txtnom.setText(dt.getValueAt(i, 2).toString()); // lorseque i=1 getValueAt nous retourne le premier ligne si i=2 le ligne ......
       txtprenom.setText(dt.getValueAt(i, 3).toString());
        combservice.setSelectedItem(dt.getValueAt(i, 4).toString());
        txtduree.setText(dt.getValueAt(i, 5).toString());
        String s = dt.getValueAt(i, 6).toString();
        if(s.equals("masculin")){jrb1.setSelected(true);}
        else {jrb2.setSelected(true);}
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur deplacement stagiaire\n"+e.getMessage());
    }
}
    
    public void actualiser(){
        txtid.setText("");
        txtmat.setText("");
        txtnom.setText("");
        txtprenom.setText("");
        combservice.setSelectedItem(1);
        jrb1.isSelected();
        txtduree.setText("");
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEST1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEST1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEST1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEST1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEST1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnn1;
    private javax.swing.JButton btnn2;
    private javax.swing.JButton btnn3;
    private javax.swing.JButton btnn4;
    private javax.swing.JButton btnn5;
    private javax.swing.JComboBox<String> combrech;
    private javax.swing.JComboBox<String> combservice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jrb1;
    private javax.swing.JCheckBox jrb2;
    private javax.swing.ButtonGroup jrbg;
    private javax.swing.JTable tblstg;
    private javax.swing.JTextField txtduree;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
}
